services:
    mlflow:
        build:
            context: .
            dockerfile: Dockerfile.mlflow
        ports:
            - "5000:5000"
        volumes:
            - "${PWD}/mlflow_data:/home/mlflow_data/"

    airflow:
        build: 
            context: .
            dockerfile: Dockerfile.airflow
        ports:
            - "8080:8080"
        environment:
            - AIRFLOW_HOME=/app/airflow  # holds airflow.cfg and password for admin
            - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_airflow/airflow
        depends_on:
            - postgres_airflow
        # command: bash -c "sleep 5 && airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && airflow webserver"
        command: bash -c "sleep 5 && airflow db migrate && airflow api-server"

    postgres_airflow:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow
        volumes:
            - "${PWD}/postgres_data:/var/lib/postgresql/data"
