FROM python:3.12-slim

RUN pip install --upgrade pip
RUN pip install boto3
RUN pip install mlflow==3.1.1

EXPOSE 5000

# CMD [ \
#     "mlflow", "server", \
#     "--backend-store-uri", "sqlite:///home/mlflow_data/mlflow.db", \
#     "--default-artifact-root", "file:///home/mlflow_data/mlflow_artifacts/", \
#     "--host", "0.0.0.0", \
#     "--port", "5000" \
# ]